resilience4j:
  timelimiter:
    instances:
      myTimeLimiter:
        timeoutDuration: 1s
  ratelimiter:
    limiters:
      myRateLimiter:
        limitForPeriod: 1
        limitRefreshPeriod: 60s
        timeoutDuration: 0

spring:
  cloud:
    gateway:
      routes:
        - id: sample-time-limit
          uri: http://localhost:8081
          predicates:
            - Path=/test1
          filters:
            - name: CircuitBreaker
              args:
                name: myTimeLimiter
                fallbackUri: forward:/defaultFallBack
        - id: sample-rate-limit
          uri: http://localhost:8081
          predicates:
            - Path=/test2
          filters:
            - name: CircuitBreaker
              args:
                name: myRateLimiter
                fallbackUri: forward:/defaultFallBack